name: ci

on:
  pull_request:
    branches: 
    - main
  workflow_dispatch:
    

jobs:
  build:
    name: 'Build & Test'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Install dependencies
      run: npm ci

    - name: Rebuild the dist directory
      run: |
        npm run build
        npm run package

