on:
  pull_request:
    branches:
    - main
    types: [closed]

name: '[autorelease] PR merged'

jobs:
  create-draft-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'autorelease')
    env:
      ARTIFACT_PATH: ${{ github.workspace }}/artifacts

    steps:
    - uses: actions/checkout@v3

      # The PR we are merging should have updated the changelog to set the target release version as the
      # latest version (this happens in prepare-release.yml)
    - name: Get latest release info
      id: get-release-info
      uses: release-flow/keep-a-changelog-action/get-release-info@v1
      with:
        release-version: latest

    - name: Display release notes
      run: |
        echo "${{ steps.get-release-info.outputs.release-notes }}"

    - name: Parse current version number
      uses: madhead/semver-utils@latest
      id: parse-semver
      with:
        version: ${{ steps.get-release-info.outputs.release-version }}

    # Build the npm package
    - name: Build dist
      run: |
        npm run clean
        npm run all

    # Update
    - name: Update NPM package version
      uses: jaywcjlove/github-action-package@v1.3.0
      with:
        version: ${{ steps.get-release-info.outputs.release-version }}


    - name: Create NPM package artifact
      run: |
        [ -d "${{ env.ARTIFACT_PATH }}" ] && rm -rf ${{ env.ARTIFACT_PATH }}
        npm pack --pack-destination ${{ env.ARTIFACT_PATH }}

    # We need to create a token
    # a) To have the GH release appear to be generated by our app instead of github-actions (cosmetic)
    # b) So we can use the same mechanism to get a token when running locally under act
    - uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.RELEASEBOT_APP_ID }}
        private_key: ${{ secrets.RELEASEBOT_PRIVATE_KEY }}
        github_api_url: ${{ github.api_url && github.api_url || 'https://api.github.com' }}

    - name: Create draft release
      id: create-release
      uses: softprops/action-gh-release@v1
      with:
        name: '${{ steps.get-release-info.outputs.release-version }}'
        tag_name: 'v${{ steps.get-release-info.outputs.release-version }}'
        body: ${{ steps.get-release-info.outputs.release-notes }}
        files: '${{ env.ARTIFACT_PATH }}/*'
        target_commitish: '${{ github.base_ref }}'
        draft: true
        prerelease: ${{ steps.parse-semver.outputs.is-prerelease }}
        token: ${{ steps.generate-token.outputs.token }}
        fail_on_unmatched_files: true

    - name: Display instructions
      run: |
        echo "::notice title=Draft Release Prepared::A draft release has been prepared for you to approve: ${{ steps.create-release.outputs.url }}"
  