on:
  release:
    types: [published]


name: '[autorelease] Release published'

jobs:
  update-ref:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Download nupkg release asset
      uses: robinraju/release-downloader@v1.7
      with:
        releaseId: '${{ github.event.release.id }}'
        fileName: "*.tgz"
        out-file-path: 'assets'

    - name: Publish NPM package
      run: |
        for file in assets/*.tgz; do 
          echo "Publishing $file"
        done

    # Setup .npmrc file to publish to GitHub Packages for this repo
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'

    - run: npm ci

    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}